# Site settings
title: 小狼书斋
motto: 严肃三观，游戏人生
email: hhfire2006@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hongheng.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  hongheng
weixin_username:  hhfire

# Build settings
markdown: kramdown
